defaults: &defaults
  

development:
  <<: *defaults


test:
  <<: *defaults


production:
  <<: *defaults
  dropbox_app_key: <%= ENV['DROPBOX_APP_KEY'] %>
  dropbox_app_secret: <%= ENV['DROPBOX_APP_SECRET'] %>
  dropbox_app_token: <%= ENV['DROPBOX_APP_KEY_TOKEN'] %>